---
- name: Starting playbook and applying roles
  hosts: containers
  gather_facts: false
  remote_user: root
  connection: docker
  vars:
    num_hosts: "{{ groups['containers'] | length }}"

  roles:
    - common
    - geekbench
